use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();

    // vlc-rs hardcodes `#[link(name = "vlc")]`; supply the directory that
    // contains vlc.lib (generated from libvlc.dll via dumpbin + lib.exe).
    println!("cargo:rustc-link-search=native={manifest_dir}/vlc-lib");

    // Copy the bundled VLC runtime (libvlc.dll, libvlccore.dll, plugins/)
    // from vlc-dist/ into the binary output directory so the app runs without
    // requiring VLC to be installed on the user's machine.
    let vlc_dist = PathBuf::from(&manifest_dir).join("vlc-dist");
    if vlc_dist.exists() {
        let out_dir = std::env::var("OUT_DIR").unwrap();
        // OUT_DIR = target/{profile}/build/{pkg}-{hash}/out  →  climb 3 levels
        let binary_dir = PathBuf::from(&out_dir)
            .ancestors()
            .nth(3)
            .expect("cannot determine binary output directory")
            .to_path_buf();
        copy_dir_all(&vlc_dist, &binary_dir);
        println!("cargo:rerun-if-changed={}", vlc_dist.display());
    }

    tauri_build::build()
}

fn copy_dir_all(src: &Path, dst: &Path) {
    for entry in std::fs::read_dir(src).expect("vlc-dist is unreadable") {
        let entry = entry.unwrap();
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_file() {
            // Skip the plugins cache: it embeds absolute paths from the source
            // machine and will be regenerated by libvlccore on first launch.
            if entry.file_name() == "plugins.dat" {
                continue;
            }
            std::fs::copy(&src_path, &dst_path).ok();
        } else if src_path.is_dir() {
            std::fs::create_dir_all(&dst_path).ok();
            copy_dir_all(&src_path, &dst_path);
        }
    }
}
