<#
.SYNOPSIS
  Build an unsigned Skald .msix from an existing release build (Microsoft Store,
  "Path B" of the publishing guide). Hand-packs the raw `tauri build` output with
  the Windows SDK's makeappx.exe - no installer-capture, no extra packager crate.

.DESCRIPTION
  Stages the runtime layout the app already expects at runtime (skald.exe + the
  bundled LibVLC/plugins + ffprobe/tone helpers, exactly as build.rs assembles
  target/release), drops in the Store tile assets (generated by `tauri icon`) and
  a token-substituted AppxManifest.xml, then runs `makeappx pack`.

  The produced .msix is UNSIGNED on purpose - Microsoft signs it at Partner Center
  ingestion. Use -Sign only to make a locally-installable package for testing
  (Add-AppxPackage refuses an unsigned package); never ship a locally-signed one.

  This is Store-only and is intentionally NOT wired into `pnpm tauri build` (that
  keeps producing the signed NSIS installer for GitHub Releases - "Path A").

.PARAMETER IdentityName
  MSIX Identity/Name. PLACEHOLDER until Partner Center reserves the app - it then
  assigns this (e.g. "1234Publisher.Skald"). A mismatch is rejected at ingestion.

.PARAMETER Publisher
  MSIX Identity/Publisher (e.g. "CN=ABCD1234-..."). Partner-Center-assigned. For
  local -Sign testing it MUST equal your test certificate's subject exactly.

.PARAMETER PublisherDisplayName
  Human-readable publisher shown in the Store / Start menu.

.PARAMETER Architecture
  Package architecture. Default x64 (Skald's target). One package per arch.

.PARAMETER Version
  Override the four-part version. Default: derived from tauri.conf.json's `version`
  by padding to four parts (1.0.0 -> 1.0.0.0). Each Store update must strictly
  increase this.

.PARAMETER Sign
  Also sign the .msix with -CertPath, for LOCAL install testing only.

.PARAMETER CertPath
  Path to a .pfx whose subject equals -Publisher. Required with -Sign.

.PARAMETER CertPassword
  Password for -CertPath (omit if the pfx has none).

.EXAMPLE
  # Unsigned package for Partner Center submission (once identity is known):
  ./build-msix.ps1 -IdentityName 1234Pub.Skald -Publisher "CN=ABCD..." -PublisherDisplayName "Jane Dev"

.EXAMPLE
  # Locally-installable test package (self-signed cert subject must match Publisher):
  ./build-msix.ps1 -Sign -CertPath .\skald-test.pfx -Publisher "CN=SkaldTest"
#>
[CmdletBinding()]
param(
  # Real Partner Center identity for "Skald for Audiobookshelf" (account: fireb).
  # These are public values (they appear in any published MSIX), safe to commit.
  [string]$IdentityName        = '46220fireb.SkaldforAudiobookshelf',
  [string]$Publisher           = 'CN=D27C5BCD-0D89-4F84-81B4-447BAF25B3BE',
  [string]$PublisherDisplayName = 'fireb',
  [ValidateSet('x64', 'x86', 'arm64')]
  [string]$Architecture        = 'x64',
  [string]$Version,
  [switch]$Sign,
  [string]$CertPath,
  [string]$CertPassword
)

$ErrorActionPreference = 'Stop'

# -- Resolve repo paths relative to this script (src-tauri/msix/) --------------
$MsixDir   = $PSScriptRoot
$SrcTauri  = Split-Path $MsixDir -Parent
$ConfPath  = Join-Path $SrcTauri 'tauri.conf.json'
$ReleaseDir = Join-Path $SrcTauri 'target\release'
$IconsDir  = Join-Path $SrcTauri 'icons'
$Template  = Join-Path $MsixDir 'AppxManifest.xml'
$Staging   = Join-Path $SrcTauri 'target\msix-layout'
$OutputDir = Join-Path $SrcTauri 'target'

# -- Locate a Windows SDK tool (makeappx / signtool) --------------------------
# Prefer PATH, else the newest x64 build under the Windows Kits bin dirs.
function Find-SdkTool([string]$Name) {
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  if ($null -ne $cmd) { return $cmd.Source }
  $roots = @("${env:ProgramFiles(x86)}\Windows Kits\10\bin", "$env:ProgramFiles\Windows Kits\10\bin")
  foreach ($root in $roots) {
    if (-not (Test-Path $root)) { continue }
    $found = Get-ChildItem -Path $root -Recurse -Filter $Name -ErrorAction SilentlyContinue |
      Where-Object { $_.FullName -match '\\x64\\' } |
      Sort-Object FullName -Descending |
      Select-Object -First 1
    if ($null -ne $found) { return $found.FullName }
  }
  return $null
}

$MakeAppx = Find-SdkTool 'makeappx.exe'
if ($null -eq $MakeAppx) {
  throw "makeappx.exe not found. Install the Windows 10/11 SDK (ships with the VS Build Tools 'Desktop development with C++' workload)."
}
Write-Host "makeappx: $MakeAppx"

# -- Derive the four-part version (MSIX requires four parts) -------------------
if ([string]::IsNullOrWhiteSpace($Version)) {
  $conf = Get-Content $ConfPath -Raw | ConvertFrom-Json
  $core = ($conf.version -split '[-+]')[0]           # strip pre-release/build metadata
  $parts = [System.Collections.ArrayList]@($core -split '\.')
  while ($parts.Count -lt 4) { [void]$parts.Add('0') }
  $Version = ($parts[0..3] -join '.')
}
if ($Version -notmatch '^\d+\.\d+\.\d+\.\d+$') {
  throw "Version '$Version' is not four-part (e.g. 1.0.0.0)."
}
Write-Host "Version:  $Version ($Architecture)"

# -- Stage a clean layout dir -------------------------------------------------
if (Test-Path $Staging) { Remove-Item $Staging -Recurse -Force }
New-Item -ItemType Directory -Force -Path $Staging | Out-Null

# Runtime files: the exe + the bundled deps build.rs copies next to it. The app
# resolves all of these from resource_dir() == the exe's directory, so a flat
# copy beside skald.exe reproduces the layout it expects.
$RuntimeFiles = @('skald.exe', 'libvlc.dll', 'libvlccore.dll', 'vlc-cache-gen.exe', 'ffprobe.exe', 'tone.exe')
foreach ($f in $RuntimeFiles) {
  $src = Join-Path $ReleaseDir $f
  if (-not (Test-Path $src)) {
    throw "Missing $src. Build a release first: 'cargo build --release' (or 'pnpm tauri build')."
  }
  Copy-Item $src (Join-Path $Staging $f) -Force
}
# LibVLC plugins tree (loaded via VLC_PLUGIN_PATH = resource_dir\plugins).
$pluginsSrc = Join-Path $ReleaseDir 'plugins'
if (-not (Test-Path $pluginsSrc)) { throw "Missing $pluginsSrc. Build a release first." }
Copy-Item $pluginsSrc (Join-Path $Staging 'plugins') -Recurse -Force

# Store tile assets (generated by `tauri icon` into icons/).
$AssetDir = Join-Path $Staging 'Assets'
New-Item -ItemType Directory -Force -Path $AssetDir | Out-Null
$Assets = @('Square150x150Logo.png', 'Square44x44Logo.png', 'Square71x71Logo.png', 'StoreLogo.png')
foreach ($a in $Assets) {
  $src = Join-Path $IconsDir $a
  if (-not (Test-Path $src)) { throw "Missing icon asset $src. Regenerate with 'pnpm tauri icon'." }
  Copy-Item $src (Join-Path $AssetDir $a) -Force
}

# -- Substitute manifest tokens -----------------------------------------------
$manifest = Get-Content $Template -Raw
$manifest = $manifest.Replace('__IDENTITY_NAME__', $IdentityName).
  Replace('__PUBLISHER__', $Publisher).
  Replace('__PUBLISHER_DISPLAY_NAME__', $PublisherDisplayName).
  Replace('__VERSION__', $Version).
  Replace('__ARCH__', $Architecture)
# makeappx requires AppxManifest.xml at the package root.
Set-Content -Path (Join-Path $Staging 'AppxManifest.xml') -Value $manifest -Encoding UTF8

if ($IdentityName -like '*Placeholder*' -or $Publisher -like '*Placeholder*') {
  Write-Warning "Using PLACEHOLDER identity. The package will pack and install locally (with -Sign) but Partner Center will reject it until you pass the reserved -IdentityName / -Publisher / -PublisherDisplayName."
}

# -- Pack ---------------------------------------------------------------------
$OutFile = Join-Path $OutputDir "Skald_${Version}_${Architecture}.msix"
if (Test-Path $OutFile) { Remove-Item $OutFile -Force }
Write-Host "Packing -> $OutFile"
& $MakeAppx pack /o /d $Staging /p $OutFile
if ($LASTEXITCODE -ne 0) { throw "makeappx pack failed (exit $LASTEXITCODE)." }

# -- Optional: sign for LOCAL install testing only ----------------------------
if ($Sign) {
  if ([string]::IsNullOrWhiteSpace($CertPath)) {
    throw "-Sign requires -CertPath: a .pfx whose subject equals the manifest Publisher ('$Publisher')."
  }
  $SignTool = Find-SdkTool 'signtool.exe'
  if ($null -eq $SignTool) { throw "signtool.exe not found (install the Windows SDK)." }
  $signArgs = @('sign', '/fd', 'SHA256', '/a', '/f', $CertPath)
  if (-not [string]::IsNullOrWhiteSpace($CertPassword)) { $signArgs += @('/p', $CertPassword) }
  $signArgs += $OutFile
  & $SignTool @signArgs
  if ($LASTEXITCODE -ne 0) { throw "signtool sign failed (exit $LASTEXITCODE)." }
  Write-Host "Signed for local testing (do NOT submit this signed artifact)."
}

Write-Host ""
Write-Host "Done: $OutFile"
if (-not $Sign) {
  Write-Host "Unsigned - submit this to Partner Center (Microsoft signs at ingestion)."
}
